# Generated by Django 6.1.1 on 2026-09-22 12:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('resource_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_code', models.CharField(max_length=50)),
                ('resource_type', models.CharField(max_length=50)),
                ('block', models.CharField(blank=True, max_length=50, null=True)),
                ('has_machines', models.BooleanField(default=False)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'resources',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=50)),
                ('can_override', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('role', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.RESTRICT, to='booking_api.role')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_type', models.CharField(max_length=50)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('purpose', models.TextField(blank=True, null=True)),
                ('headcount', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DENIED', 'Denied'), ('CANCELLED', 'Cancelled'), ('PREEMPTED', 'Preempted'), ('COMPLETED', 'Completed')], default='PENDING', max_length=30)),
                ('decision_reason', models.TextField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('series_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, db_column='approved_by', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='approved_bookings', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(db_column='requested_by', on_delete=django.db.models.deletion.RESTRICT, related_name='requested_bookings', to=settings.AUTH_USER_MODEL)),
                ('resource', models.ForeignKey(db_column='resource_id', on_delete=django.db.models.deletion.RESTRICT, related_name='bookings', to='booking_api.resource')),
            ],
            options={
                'db_table': 'bookings',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('booking', models.ForeignKey(blank=True, db_column='booking_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='booking_api.booking')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('audit_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=50)),
                ('target_entity_type', models.CharField(blank=True, max_length=50, null=True)),
                ('target_entity_id', models.IntegerField(blank=True, null=True)),
                ('previous_state', models.TextField(blank=True, null=True)),
                ('new_state', models.TextField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor_user', models.ForeignKey(db_column='actor_user_id', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(blank=True, db_column='booking_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking_api.booking')),
                ('resource', models.ForeignKey(blank=True, db_column='resource_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking_api.resource')),
            ],
            options={
                'db_table': 'audit_logs',
            },
        ),
    ]
